In [7]:
#Dependencies
from splinter import Browser
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import time
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

In [8]:

#configue setting for splinter
browser = Browser("chrome")

In [9]:
# Visit the following URL
url = "https://www.kj.com/blog/wine-101-what-temperature-should-my-wine-be"
tables = pd.read_html(url)
wine_temperature = tables[0]
wine_temperature

,0,1,2
0,Wine Varietal,Suggested Serving Temperature,Chill in Fridge Approx. (from room temp)
1,Champagne or Sparkling Wine,45°F,30-40 minutes
2,Pinot Gris,45-50°F,30-40 minutes
3,Riesling,45-50°F,30-40 minutes
4,Sauvignon Blanc,45-50°F,30-40 minutes
5,Chardonnay,50°F,30 minutes
6,Rosé,50°F,30 minutes
7,Viognier,50°F,30 minutes
8,White Bordeaux Blends,50°F,30 minutes
9,Pinot Noir,55°F-60°F,15-20 minutes
10,Cabernet Franc,60°F,15 minutes
11,Syrah,60°F-65°F,10-15 minutes
12,Zinfandel,60°F-65°F,10-15 minutes
13,Merlot,60°F-65°F,10-15 minutes
14,Cabernet Sauvignon,60°F-65°F,10-15 minutes
15,Malbec,60°F-65°F,10-15 minutes
16,Red Bordeaux Blends,60°F-65°F,10-15 minutes

In [10]:
wine_temperature.to_csv("Resources/wine-temperature.csv", index=False, header=True)

In [11]:
# Visit the following URL
url2 = "https://www.wineware.co.uk/decanting/perfect-drinking-temperature-for-wine"
tables2 = pd.read_html(url2)
wine_temperature2 = tables2[0]
wine_temperature2

,Wine,Type,Temperature (˚F),Temperature (˚C)
0,Vintage Port,Fortified Wine,66˚F,19˚C
1,"Bordeaux, Shiraz",Red Wine,64˚F,18˚C
2,"Red Burgundy, Cabernet",Red Wine,63˚F,17˚C
3,"Rioja, Pinot Noir",Red Wine,61˚F,16˚C
4,"Chianti, Zinfandel",Red Wine,59˚F,15˚C
5,Tawny/NV Port,Fortified Wine,57˚F,14˚C
6,"Beaujolais, Rosé",White Wine / Rosé,54˚F,12˚C
7,"Viognier, Sauternes",White Wine,52˚F,11˚C
8,Chardonnay,White Wine,48˚F,9˚C
9,Riesling,White Wine,47˚F,8˚C
10,"Champagne, Sparkling Wine, Dessert Wine*Tip - ...",Sparkling Wine,45˚F,7˚C
11,Ice Wines,Dessert Wine,43˚F,6˚C
12,Asti Spumanti,Sparkling Wine,41˚F,5˚C

In [12]:
wine_temperature2.to_csv("Resources/wine-temperature2.csv", index=False, header=True)

In [13]:
# define url and open in browser

url3 = "https://winefolly.com/wine-pairing/12-classic-wine-and-cheese-pairings-you-have-to-try/"
browser.visit(url3)

In [14]:
# Parse HTML with Beautiful Soup
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

#finding titles of hemispheres
titles = soup.find_all('h3')
top_titles = []
# Print only the headlines
for x in range(len(titles)):
    temp=titles[x].text
#     newvar = temp.strip('\n\n')
#     newvar2 = newvar.strip('and')
    top_titles.append(temp)
df = pd.DataFrame([top_titles])

data = df.T
data


# new data frame with split value columns 
new = data[0].str.split(" and ", n = 1, expand = True) 
  
# making separate first name column from new data frame 
data["Wine"]= new[0] 
  
# making separate last name column from new data frame 
data["Cheese"]= new[1] 
  
# Dropping old Name columns 
data.drop(columns =[0], inplace = True) 
wine_cheese = data[:-1]
wine_cheese

                                       Wine            Cheese
0                                Pinot Noir           Gruyere
1   The Age-Old Partnership - Wine & Cheese              None
2                                 Aged Port      Blue Stilton
3                                 Champagne              Brie
4                            Moscato d’Asti        Gorgonzola
5                               Tempranillo         Idiazabal
6                           Sauvignon Blanc       Goat Cheese
7                        Cabernet Sauvignon      Aged Cheddar
8                             Provence Rosé           Havarti
9                                  Riesling          Raclette
10                         Chianti Classico  Pecorino Toscano
11                               Vermentino       Fiore Sardo
12                                   Malbec              Edam
13                      Pairing wine is fun              None

In [15]:
wine_cheese.to_csv("Resources/wine-cheese.csv", index=False, header=True)

In [16]:
# Visit the following URL
url = "https://home.binwise.com/blog/aged-wine#toc-wine-aging-chart"
chart_usa = pd.read_html(url)
chart_usa[0]
vintage_chart_usa= chart_usa[0]
vintage_chart_usa

                  Wine  Color Aging Window (Years)
0                 Port    Red                10–50
1               Merlot    Red                 3–15
2               Malbec    Red                 5–10
3           Sangiovese    Red                10–30
4           Monastrell    Red                 7–20
5       Cabernet Franc    Red                 5–12
6             Nebbiolo    Red                15–40
7                Syrah    Red                 2–12
8   Cabernet Sauvignon    Red                 5–25
9           Chardonnay  White                 2–10
10            Riesling  White                  0–5
11            Viognier  White                  2–7
12      White Bordeaux  White                  3–5
13            Semillon  White                  1–5
14        Chenin Blanc  White                  1–7

In [17]:
vintage_chart_usa.to_csv("Resources/wine-aging.csv", index=False, header=True)

In [20]:
# Visit the following URL
url5= "https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature"
world_temp = pd.read_html(url5)
world_temp[0]
world_temperature= world_temp[0]
world_temperature

          Country Average yearly temperature (1961–1990, degrees Celsius)
0    Burkina Faso                                              28.29
1            Mali                                              28.25
2        Kiribati                                              28.20
3        Djibouti                                              28.00
4          Tuvalu                                              28.00
..            ...                                                ...
186    Kyrgyzstan                                              01.55
187        Norway                                              01.50
188      Mongolia                                              −0.70
189        Russia                                              −5.10
190        Canada                                              −5.35

[191 rows x 2 columns]

In [21]:
world_temperature.to_csv("Resources/world_temperature.csv", index=False, header=True)